
const SEED=window.JOBSEARCH_SEED||[];const META=window.JOBSEARCH_META||{};
const APP_KEY='JobSearch.data.v2',SNAP_KEY='JobSearch.snapshots.v2',SETTINGS_KEY='JobSearch.settings.v2';
const PHONE='(83) 9 9900-8017';const MAX_SNAPSHOTS=40;let items=loadItems(),mode='all',editing=null,current=null,dirty=false,saveTimer=null,deferredInstall=null;
const statuses=['Não iniciado','Pesquisar canal','Pronto para enviar','Enviado','Follow-up','Respondeu','Entrevista','Banco de talentos','Sem retorno','Encerrado'];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function today(){return new Date().toISOString().slice(0,10)}function plus(d,n){const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1900)}
function loadItems(){try{const v=localStorage.getItem(APP_KEY);return v?JSON.parse(v):structuredClone(SEED)}catch{return structuredClone(SEED)}}
function profile(seg){if(seg==='Indústria e distribuição')return 'Tenho experiência em apoio administrativo e comercial, atendimento a gestores, vendedores e clientes, organização de estoque e processos, planilhas, relatórios e dashboards.';if(seg==='Varejo e shopping')return 'Tenho experiência com atendimento ao cliente, caixa, estoque, cadastro de mercadorias, apoio administrativo e comercial e organização de processos.';if(seg==='Saúde')return 'Tenho experiência com atendimento presencial e digital, organização de documentos e processos, planilhas, relatórios e suporte administrativo e técnico.';if(seg==='Educação')return 'Tenho vivência em apoio técnico-administrativo na UFRN, suporte de TI, atendimento, documentos, planilhas e relatórios, além de experiência como monitor acadêmico.';if(seg==='Telecom e tecnologia')return 'Sou estudante de Sistemas de Informação e possuo experiência com suporte técnico, atendimento a usuários, sistemas, planilhas e relatórios.';if(seg==='Financeiro e cooperativas')return 'Tenho experiência em atendimento, rotinas administrativas, planilhas, relatórios e indicadores, além de perfil analítico, organizado e comunicativo. Tenho interesse inclusive em estágio.';if(seg==='Remoto')return 'Tenho experiência em atendimento, apoio administrativo, suporte técnico, planilhas e ferramentas digitais. Possuo estrutura para trabalho remoto e disponibilidade de horário.';if(seg==='Setor público e institucional')return 'Tenho experiência em apoio técnico-administrativo na UFRN, atendimento, documentos, planilhas, relatórios e suporte de TI.';return 'Tenho experiência em apoio administrativo, atendimento, organização de processos, planilhas, relatórios, dashboards e suporte a equipes.'}
function message(c){if(c.message)return c.message;const local=c.modality.startsWith('Presencial')?'Estou estabelecendo residência em Patos-PB':'Resido em Patos-PB e tenho estrutura para trabalho totalmente remoto';return `Olá, equipe de ${c.sector} da ${c.company}! Meu nome é Renan Costa.\n\n${local} e gostaria de colocar meu currículo à disposição para oportunidades em ${c.targetRoles}.\n\n${profile(c.segment)} Sou organizado, responsável, proativo e tenho disponibilidade para trabalhar em qualquer horário.\n\nAcredito que meu perfil pode contribuir com a equipe e fico à disposição para processos atuais ou futuros. Encaminho meu currículo para avaliação.\n\nAtenciosamente,\nRenan Costa\nTelefone/WhatsApp: ${PHONE}`}
function byid(id){return items.find(x=>x.id===id)}function copy(t){navigator.clipboard?.writeText(t).then(()=>toast('Copiado.')).catch(()=>{const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();toast('Copiado.')})}
function settings(){try{return JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}catch{return {}}}function setSettings(s){localStorage.setItem(SETTINGS_KEY,JSON.stringify({...settings(),...s}))}
function checksum(v){let h=2166136261,s=JSON.stringify(v);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function snapshots(){try{return JSON.parse(localStorage.getItem(SNAP_KEY)||'[]')}catch{return []}}
function createSnapshot(reason='automático',force=false){const list=snapshots(),hash=checksum(items),last=list[0];if(!force&&last&&last.hash===hash)return;const now=new Date();if(!force&&last&&now-new Date(last.createdAt)<120000)return;list.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),createdAt:now.toISOString(),reason,hash,count:items.length,data:structuredClone(items)});localStorage.setItem(SNAP_KEY,JSON.stringify(list.slice(0,MAX_SNAPSHOTS)));updateBackupStatus('local')}
function save(reason='alteração'){localStorage.setItem(APP_KEY,JSON.stringify(items));dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{createSnapshot(reason);autoFileBackup()},1500);render()}
function resetSeed(){if(confirm('Restaurar a base inicial do projeto? Exporte um backup antes.')){createSnapshot('antes de restaurar',true);items=structuredClone(SEED);save('base restaurada');toast('Base inicial restaurada.')}}
function filtered(){const q=$('#q').value.toLowerCase(),fm=$('#fm').value,fs=$('#fs').value,fp=$('#fp').value,fst=$('#fst').value,fc=$('#fc').value;return items.filter(c=>{if(mode==='local'&&!c.modality.startsWith('Presencial'))return false;if(mode==='remote'&&!c.modality.startsWith('Remoto'))return false;if(mode==='due'&&(!c.followUpDate||c.followUpDate>today()||['Entrevista','Encerrado'].includes(c.status)))return false;if(q&&![c.company,c.segment,c.targetRoles,c.sector,c.contact,c.notes,c.confidence].join(' ').toLowerCase().includes(q))return false;if(fm&&c.modality!==fm)return false;if(fs&&c.segment!==fs)return false;if(fp&&c.priority!==fp)return false;if(fst&&c.status!==fst)return false;if(fc&&c.confidence!==fc)return false;return true}).sort((a,b)=>a.priority.localeCompare(b.priority)||b.compatibility-a.compatibility||a.company.localeCompare(b.company))}
function stats(){const total=items.length,local=items.filter(x=>x.modality.startsWith('Presencial')).length,remote=items.filter(x=>x.modality.startsWith('Remoto')).length,sent=items.filter(x=>x.sent||['Enviado','Follow-up','Respondeu','Entrevista'].includes(x.status)).length,interviews=items.filter(x=>x.status==='Entrevista').length,due=items.filter(x=>x.followUpDate&&x.followUpDate<=today()&&!['Entrevista','Encerrado'].includes(x.status)).length;for(const [k,v]of Object.entries({total,local,remote,sent,interviews,due}))document.querySelector(`[data-s=${k}]`).textContent=v;const p=total?Math.round(sent/total*100):0;$('#pct').textContent=p+'%';$('#pctbar').style.width=p+'%'}
function render(){stats();const r=filtered();$('#count').textContent=r.length+' alvo(s)';$('#tbody').innerHTML=r.map(c=>`<tr><td><input class="check" type="checkbox" ${c.sent?'checked':''} onchange="sent('${c.id}',this.checked)"></td><td><div class="company">${esc(c.company)}</div><div class="sub">${esc(c.city)} · ${esc(c.modality)}</div></td><td><span class="badge ${c.priority}">${c.priority}</span><div class="bar"><i style="width:${c.compatibility}%"></i></div><div class="sub">${c.compatibility}%</div></td><td><div>${esc(c.segment)}</div><div class="sub truncate" title="${esc(c.targetRoles)}">${esc(c.targetRoles)}</div></td><td><div>${esc(c.sector)}</div><div class="sub">${esc(c.channelType)}</div><span class="confidence">${esc(c.confidence||'A confirmar')}</span></td><td class="truncate" title="${esc(c.contact)}">${esc(c.contact)}</td><td><select class="status" onchange="statusChange('${c.id}',this.value)">${statuses.map(s=>`<option ${c.status===s?'selected':''}>${s}</option>`).join('')}</select><div class="sub">${c.followUpDate?'Follow-up: '+c.followUpDate:''}</div></td><td><div class="row-actions"><button class="btn" onclick="details('${c.id}')">Ver</button><button class="btn" onclick="copyPack('${c.id}')">Copiar</button><button class="btn" onclick="editItem('${c.id}')">Editar</button></div></td></tr>`).join('');$('#cards').innerHTML=r.map(c=>`<article class="card"><div style="display:flex;justify-content:space-between"><div class="company">${esc(c.company)}</div><span class="badge ${c.priority}">${c.priority}</span></div><div class="sub">${esc(c.modality)} · ${c.compatibility}%</div><p><b>Setor:</b> ${esc(c.sector)}</p><p><b>Cargos:</b> ${esc(c.targetRoles)}</p><span class="confidence">${esc(c.confidence||'A confirmar')}</span><div class="row-actions" style="margin-top:10px"><button class="btn" onclick="details('${c.id}')">Abrir</button><button class="btn" onclick="copyPack('${c.id}')">Copiar</button><button class="btn" onclick="sent('${c.id}',true)">Enviado</button></div></article>`).join('');$('#empty').style.display=r.length?'none':'block'}
function sent(id,v){const c=byid(id);c.sent=v;if(v){c.sentDate=c.sentDate||today();c.lastContact=today();c.followUpDate=c.followUpDate||plus(today(),7);if(['Não iniciado','Pesquisar canal','Pronto para enviar'].includes(c.status))c.status='Enviado'}else{c.sentDate='';if(c.status==='Enviado')c.status='Não iniciado'}save('envio atualizado');toast(v?'Envio registrado.':'Marcação removida.')}
function statusChange(id,v){const c=byid(id);c.status=v;if(['Enviado','Follow-up','Respondeu','Entrevista'].includes(v)){c.sent=true;c.sentDate=c.sentDate||today();c.lastContact=today();c.followUpDate=c.followUpDate||plus(today(),7)}save('status atualizado')}
function copyPack(id){const c=byid(id);copy(`Assunto: ${c.subject}\n\n${message(c)}`)}
function details(id){current=id;const c=byid(id);$('#dt').textContent=c.company;$('#db').innerHTML=`<dl class="details"><dt>Modalidade</dt><dd>${esc(c.modality)}</dd><dt>Prioridade</dt><dd>${c.priority} · ${c.compatibility}%</dd><dt>Confiabilidade</dt><dd>${esc(c.confidence||'A confirmar')}</dd><dt>Setor</dt><dd>${esc(c.sector)}</dd><dt>Cargos</dt><dd>${esc(c.targetRoles)}</dd><dt>Canal</dt><dd>${esc(c.channelType)}</dd><dt>Contato</dt><dd>${esc(c.contact)}</dd><dt>Assunto</dt><dd>${esc(c.subject)} <button class="btn" onclick="copy(byid('${id}').subject)">Copiar</button></dd><dt>Mensagem</dt><dd><div class="message">${esc(message(c))}</div><br><button class="btn" onclick="copy(message(byid('${id}')))">Copiar mensagem</button> <button class="btn" onclick="copyPack('${id}')">Copiar pacote</button></dd><dt>Canal/fonte</dt><dd>${c.sourceUrl?`<a href="${esc(c.sourceUrl)}" target="_blank" rel="noopener">Abrir</a>`:'Não informado'}<div class="sub">${esc(c.sourceName||'')}</div></dd><dt>Verificado em</dt><dd>${esc(c.verifiedAt||'—')}</dd><dt>Datas</dt><dd>Enviado: ${c.sentDate||'—'} | Follow-up: ${c.followUpDate||'—'} | Último contato: ${c.lastContact||'—'}</dd><dt>Observações</dt><dd>${esc(c.notes||'—')}</dd></dl>`;$('#details').classList.add('open')}
function closeM(id){$('#'+id).classList.remove('open')}function editItem(id=null){editing=id;const c=id?byid(id):{company:'',city:'Patos-PB',modality:'Presencial em Patos',segment:'Serviços e consultoria',priority:'B',compatibility:80,sector:'RH / Administrativo',targetRoles:'Assistente administrativo ou suporte',channelType:'Pesquisar canal',contact:'',sourceUrl:'',notes:'',verifiedAt:today(),status:'Não iniciado',sentDate:'',followUpDate:'',lastContact:'',subject:'',message:'',confidence:'Contato a confirmar',sourceName:'Cadastro manual'};const f=$('#form');for(const k in c)if(f.elements[k]&&typeof c[k]!=='object')f.elements[k].value=c[k]??'';if(id&&!c.message)f.elements.message.value=message(c);$('#ft').textContent=id?'Editar empresa':'Adicionar empresa';$('#editor').classList.add('open')}
function removeCurrent(){if(current&&confirm('Excluir este registro?')){createSnapshot('antes de excluir',true);items=items.filter(x=>x.id!==current);save('registro excluído');closeM('details');toast('Excluído.')}}
function download(n,c,t){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function exportPayload(){return{project:'JobSearch',version:META.version||'2.0.0',exportedAt:new Date().toISOString(),meta:META,items}}
function exportJSON(){download(`JobSearch-backup-${today()}.json`,JSON.stringify(exportPayload(),null,2),'application/json')}
function exportCSV(){const cols=['company','city','modality','segment','priority','compatibility','sector','targetRoles','channelType','contact','confidence','subject','message','status','sentDate','followUpDate','lastContact','notes','sourceUrl'];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';download(`JobSearch-${today()}.csv`,'\ufeff'+[cols.join(';'),...items.map(c=>cols.map(k=>q(k==='message'?message(c):c[k])).join(';'))].join('\n'),'text/csv;charset=utf-8')}
function importData(raw){const d=JSON.parse(raw),arr=Array.isArray(d)?d:d.items;if(!Array.isArray(arr))throw new Error('Formato inválido');createSnapshot('antes de importar',true);items=arr;save('backup importado');toast('Backup importado.')}
$('#importer').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{importData(r.result)}catch(x){alert('Arquivo de backup inválido.')}};r.readAsText(f);e.target.value=''})
function view(v,b){mode=v;$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}function clearFilters(){['q','fm','fs','fp','fst','fc'].forEach(x=>$('#'+x).value='');render()}
$('#form').addEventListener('submit',e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.compatibility=Number(o.compatibility)||0;if(!o.subject)o.subject='Currículo – Renan Costa – '+o.targetRoles.split(',')[0];if(editing){const i=items.findIndex(x=>x.id===editing);items[i]={...items[i],...o}}else{items.push({...o,id:'EMP-'+Date.now(),sent:false,tags:[]})}save('registro salvo');closeM('editor');toast('Salvo.')});

// Backup automático: snapshots locais sempre; arquivo automático quando o navegador permite e o usuário autoriza.
const DB='JobSearchHandles',STORE='handles',HANDLE_KEY='autoBackup';
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function dbGet(k){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function dbSet(k,v){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}async function dbDel(k){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(k);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
function updateBackupStatus(state,text){const e=$('#backupStatus');e.className='backup-status '+(state==='ok'?'ok':state==='warn'?'warn':'');e.innerHTML=`<span class="dot"></span>${text||({ok:'Backup automático ativo',local:'Snapshot local salvo',warn:'Somente backup local'}[state]||'Backup local ativo')}`}
async function enableAutoBackup(){if(!('showSaveFilePicker'in window)){updateBackupStatus('warn','Navegador sem backup em arquivo');alert('O backup automático em arquivo funciona no Chrome ou Edge quando o site está hospedado em HTTPS. Os snapshots locais continuam ativos.');return}try{let h=await dbGet(HANDLE_KEY);if(h){const permission=await h.requestPermission({mode:'readwrite'});if(permission==='granted'){setSettings({autoFile:true});dirty=true;await writeBackupFile(h);updateBackupStatus('ok');toast('Backup automático reativado.');return}}h=await showSaveFilePicker({suggestedName:'JobSearch-backup-auto.json',types:[{description:'Backup JSON',accept:{'application/json':['.json']}}]});await dbSet(HANDLE_KEY,h);setSettings({autoFile:true});dirty=true;await writeBackupFile(h);updateBackupStatus('ok');toast('Backup automático em arquivo ativado.')}catch(e){if(e.name!=='AbortError')alert('Não foi possível ativar o backup automático.') }}
async function writeBackupFile(h){const p=await h.queryPermission({mode:'readwrite'});if(p!=='granted')throw new Error('permission');const w=await h.createWritable();await w.write(JSON.stringify(exportPayload(),null,2));await w.close();dirty=false;setSettings({lastAutoBackup:new Date().toISOString()});updateBackupStatus('ok')}
async function autoFileBackup(){const s=settings();if(!s.autoFile||!dirty)return;try{const h=await dbGet(HANDLE_KEY);if(!h){updateBackupStatus('warn');return}await writeBackupFile(h)}catch{updateBackupStatus('warn','Autorize novamente o arquivo')}}
async function disableAutoBackup(){await dbDel(HANDLE_KEY);setSettings({autoFile:false});updateBackupStatus('local','Backup local ativo');toast('Backup em arquivo desativado.')}
async function initBackup(){createSnapshot('inicialização');const s=settings();if(s.autoFile){try{const h=await dbGet(HANDLE_KEY);if(h&&(await h.queryPermission({mode:'readwrite'}))==='granted'){updateBackupStatus('ok');return}}catch{}}updateBackupStatus('local','Backup local ativo')}
function openSnapshots(){const list=snapshots();$('#snapshotList').innerHTML=list.length?list.map(x=>`<div class="snapshot"><div><strong>${new Date(x.createdAt).toLocaleString('pt-BR')}</strong><small>${esc(x.reason)} · ${x.count} registros · ${x.hash}</small></div><div class="row-actions"><button class="btn" onclick="restoreSnapshot('${x.id}')">Restaurar</button><button class="btn" onclick="downloadSnapshot('${x.id}')">Baixar</button></div></div>`).join(''):'<div class="empty">Nenhum snapshot disponível.</div>';$('#snapshots').classList.add('open')}
function restoreSnapshot(id){const x=snapshots().find(s=>s.id===id);if(x&&confirm('Restaurar esta versão? O estado atual será salvo antes.')){createSnapshot('antes de restaurar',true);items=structuredClone(x.data);save('snapshot restaurado');closeM('snapshots');toast('Versão restaurada.')}}function downloadSnapshot(id){const x=snapshots().find(s=>s.id===id);if(x)download(`JobSearch-snapshot-${x.createdAt.slice(0,19).replace(/:/g,'-')}.json`,JSON.stringify({project:'JobSearch',exportedAt:x.createdAt,items:x.data},null,2),'application/json')}
setInterval(()=>{if(dirty)autoFileBackup();createSnapshot('intervalo automático')},15*60*1000);window.addEventListener('beforeunload',()=>localStorage.setItem(APP_KEY,JSON.stringify(items)));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').style.display='inline-block'});async function installApp(){if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').style.display='none'}
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
const seg=[...new Set(items.map(x=>x.segment))].sort(),conf=[...new Set(items.map(x=>x.confidence).filter(Boolean))].sort();$('#fs').innerHTML='<option value="">Todos</option>'+seg.map(x=>`<option>${esc(x)}</option>`).join('');$('#fc').innerHTML='<option value="">Todas</option>'+conf.map(x=>`<option>${esc(x)}</option>`).join('');$('#fst').innerHTML='<option value="">Todos</option>'+statuses.map(x=>`<option>${x}</option>`).join('');$('#formStatus').innerHTML=statuses.map(x=>`<option>${x}</option>`).join('');['q','fm','fs','fp','fst','fc'].forEach(id=>$('#'+id).addEventListener(id==='q'?'input':'change',render));initBackup();render();
